name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  DOTNET_NOLOGO: true

jobs:

  build_and_test_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build version prefix/suffix
        run: |
          echo "VERSION_PREFIX=${{ github.run_number }}.0.0" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=alpha" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - run: dotnet pack --configuration Release --no-build --output ./artifacts -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NuGetPackage.${{ env.VERSION_PREFIX }}-${{ env.VERSION_SUFFIX }}.nupkg.zip
          path: ./artifacts/*
